# Generated by Django 3.2.8 on 2021-11-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articolo',
            name='contenuto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articolo',
            name='giornalista',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='news.giornalista'),
        ),
        migrations.AddField(
            model_name='articolo',
            name='titolo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
